- name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish/
        server-dir: /site1/
        exclude: |
          **/appsettings.json
          **/appsettings.Development.json
          **/.git*

    - name: Remove app_offline
      run: |
        curl --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" \
             -X DELE ftp://${{ secrets.FTP_SERVER }}/site1/app_offline.htm || true